dtb-$(CONFIG_ARCH_BCM_IPROC) += bcm958742k.dtb
dtb-$(CONFIG_ARCH_BCM_IPROC) += bcm958742k-diag.dtb
dtb-$(CONFIG_ARCH_BCM_IPROC) += bcm958742k-extsram.dtb
dtb-$(CONFIG_ARCH_BCM_IPROC) += bcm958742k-diag-extsram.dtb
dtb-$(CONFIG_ARCH_BCM_IPROC) += bcm958742k-initrd-extsram-tinyboot.dtb
dtb-$(CONFIG_ARCH_BCM_IPROC) += bcm958742k-paxc.dtb
dtb-$(CONFIG_ARCH_BCM_IPROC) += bcm958742k-paxc-extsram.dtb
dtb-$(CONFIG_ARCH_BCM_IPROC) += bcm958742k-qa1-i2c-extsram.dtb
dtb-$(CONFIG_ARCH_BCM_IPROC) += bcm958742k-qa2-gpioc-extsram.dtb

dts-dirs	:= emulator
always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
