dtb-$(CONFIG_ARCH_BCM_IPROC) += ns2-svk.dtb ns2-b0-svk.dtb
dtb-$(CONFIG_ARCH_BCM_IPROC) += pegasus-palladium.dtb
dtb-$(CONFIG_ARCH_BCM_IPROC) += stingray-palladium.dtb stingray-pd-paxc-chimp.dtb stingray-pd-paxb.dtb stingray-pd-usb.dtb
dtb-$(CONFIG_ARCH_BCM_IPROC) += bcm958742k-diag.dtb stingray-pd-sata.dtb
dtb-$(CONFIG_ARCH_BCM_IPROC) += bcm958742k.dtb
dtb-$(CONFIG_ARCH_BCM_IPROC) += bcm958742k-extsram.dtb
dtb-$(CONFIG_ARCH_BCM2835) += bcm2837-rpi-3-b.dtb
dtb-$(CONFIG_ARCH_VULCAN) += vulcan-eval.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
