dtb-$(CONFIG_ARCH_BCM_IPROC) += ns2-svk.dtb
dtb-$(CONFIG_ARCH_BCM_IPROC) += pegasus-palladium.dtb
dtb-$(CONFIG_ARCH_BCM_IPROC) += stingray-palladium.dtb stingray-pd-paxc-chimp.dtb stingray-pd-paxb.dtb
dtb-$(CONFIG_ARCH_BCM_IPROC) += stingray-svk-diag.dtb
dtb-$(CONFIG_ARCH_VULCAN) += vulcan-eval.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
