# Makefile for Broadcom PDC Mailbox driver

# Uncomment to enable debug tracing in the PDC driver
# CFLAGS_pdc.o := -DDEBUG
# CFLAGS_pdc_debug.o := -DDEBUG

pdc-mbox-objs := pdc.o pdc_debug.o
obj-$(CONFIG_BCM_PDC_MBOX) := pdc-mbox.o
