obj-$(CONFIG_BRCM_SMARTCARD) += smartcard.o
smartcard-objs := sci.o
smartcard-objs += bscd.o
smartcard-objs += bscd_isopriv.o
smartcard-objs += bscd_priv.o
smartcard-objs += fs.o
smartcard-objs += bscd_tpdu_t1.o
