# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_BCM_IPROC) += bcm91140x15-entphn.dtb
dtb-$(CONFIG_ARCH_BCM_IPROC) += bcm91140x15-entphn-optee.dtb
dtb-$(CONFIG_ARCH_BCM_IPROC) += bcm958313-wa.dtb
dtb-$(CONFIG_ARCH_BCM_IPROC) += bcm958313-wa-optee.dtb
dtb-$(CONFIG_ARCH_BCM_IPROC) += bcm95831x15k.dtb
dtb-$(CONFIG_ARCH_BCM_IPROC) += bcm95831x17k.dtb
dtb-$(CONFIG_ARCH_BCM_IPROC) += bcm95831x17k-optee.dtb

subdir-y	:= emulator
