# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_BCM_IPROC) += bcm95831x17k.dtb
dtb-$(CONFIG_ARCH_BCM_IPROC) += bcm95831x17k-optee.dtb

dts-dirs	:= emulator
always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
