obj-$(CONFIG_FB_BRCM_IPROC) += bcm_iproc_axipv.o
obj-$(CONFIG_FB_BRCM_IPROC) += bcm_iproc_pv.o
obj-$(CONFIG_FB_BRCM_IPROC) += bcm_iproc_dsi_panel.o
obj-$(CONFIG_FB_BRCM_IPROC) += bcm_iproc_dsi_lowlevel.o
obj-$(CONFIG_FB_BRCM_IPROC) += bcm_iproc_dsi.o
obj-$(CONFIG_FB_BRCM_IPROC) += bcm_iproc_dsi_ctrl.o
