# BCM2835 Platform Support
snd-soc-bcm2835-i2s-objs := bcm2835-i2s.o

obj-$(CONFIG_SND_BCM2835_SOC_I2S) += snd-soc-bcm2835-i2s.o

# CYGNUS Platform Support
snd-soc-cygnus-objs := cygnus-pcm.o cygnus-ssp.o

obj-$(CONFIG_SND_SOC_CYGNUS) += snd-soc-cygnus.o

# Machine module for the bcm911360_entphn (Cygnus SoC with CS42L73 codec)
snd-soc-cygnus-voipphone-machine-objs := bcm911360_entphn-machine.o

obj-$(CONFIG_SND_SOC_CYGNUS_VOIPPHONE_MACHINE) += snd-soc-cygnus-voipphone-machine.o