dtb-$(CONFIG_ARCH_BCM_IPROC) += bcm958804a8046i.dtb
dtb-$(CONFIG_ARCH_BCM_IPROC) += bcm958804a8046i-diag.dtb
dtb-$(CONFIG_ARCH_BCM_IPROC) += bcm958804a8046i-paxb-iommu.dtb
dtb-$(CONFIG_ARCH_BCM_IPROC) += bcm958804a8046i-pcie-iommu.dtb
